name: ecommerce_sqflite
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.4
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          style: italic
